// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sum/sumpb/sum.proto

package sumpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Suming struct {
	Number_1             int64    `protobuf:"varint,1,opt,name=number_1,json=number1,proto3" json:"number_1,omitempty"`
	Number_2             int64    `protobuf:"varint,2,opt,name=number_2,json=number2,proto3" json:"number_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suming) Reset()         { *m = Suming{} }
func (m *Suming) String() string { return proto.CompactTextString(m) }
func (*Suming) ProtoMessage()    {}
func (*Suming) Descriptor() ([]byte, []int) {
	return fileDescriptor_sum_f4a4fa1f1cc579b4, []int{0}
}
func (m *Suming) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suming.Unmarshal(m, b)
}
func (m *Suming) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suming.Marshal(b, m, deterministic)
}
func (dst *Suming) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suming.Merge(dst, src)
}
func (m *Suming) XXX_Size() int {
	return xxx_messageInfo_Suming.Size(m)
}
func (m *Suming) XXX_DiscardUnknown() {
	xxx_messageInfo_Suming.DiscardUnknown(m)
}

var xxx_messageInfo_Suming proto.InternalMessageInfo

func (m *Suming) GetNumber_1() int64 {
	if m != nil {
		return m.Number_1
	}
	return 0
}

func (m *Suming) GetNumber_2() int64 {
	if m != nil {
		return m.Number_2
	}
	return 0
}

type SumRequest struct {
	Suming               *Suming  `protobuf:"bytes,1,opt,name=suming,proto3" json:"suming,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sum_f4a4fa1f1cc579b4, []int{1}
}
func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (dst *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(dst, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetSuming() *Suming {
	if m != nil {
		return m.Suming
	}
	return nil
}

type SumResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sum_f4a4fa1f1cc579b4, []int{2}
}
func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (dst *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(dst, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Suming)(nil), "sum.Suming")
	proto.RegisterType((*SumRequest)(nil), "sum.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "sum.SumResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SumServiceClient is the client API for SumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type sumServiceClient struct {
	cc *grpc.ClientConn
}

func NewSumServiceClient(cc *grpc.ClientConn) SumServiceClient {
	return &sumServiceClient{cc}
}

func (c *sumServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/sum.SumService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumServiceServer is the server API for SumService service.
type SumServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
}

func RegisterSumServiceServer(s *grpc.Server, srv SumServiceServer) {
	s.RegisterService(&_SumService_serviceDesc, srv)
}

func _SumService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sum.SumService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sum.SumService",
	HandlerType: (*SumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sum/sumpb/sum.proto",
}

func init() { proto.RegisterFile("sum/sumpb/sum.proto", fileDescriptor_sum_f4a4fa1f1cc579b4) }

var fileDescriptor_sum_f4a4fa1f1cc579b4 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0xca, 0xc2, 0x30,
	0x10, 0x84, 0xff, 0xfe, 0xc5, 0x54, 0xb7, 0x07, 0x25, 0x82, 0x54, 0x4f, 0x12, 0x11, 0xc4, 0x43,
	0xa5, 0xf1, 0xe2, 0xc9, 0x83, 0x8f, 0x90, 0xdc, 0xbc, 0x08, 0x95, 0x20, 0x05, 0xd3, 0xd6, 0x6c,
	0xd7, 0xe7, 0x97, 0xa6, 0x15, 0x7b, 0x59, 0x98, 0x1d, 0xe6, 0x1b, 0x06, 0xe6, 0x48, 0xf6, 0x80,
	0x64, 0xeb, 0xbc, 0xbd, 0x69, 0xed, 0xaa, 0xa6, 0xe2, 0x21, 0x92, 0x15, 0x67, 0x60, 0x9a, 0x6c,
	0x51, 0x3e, 0xf8, 0x12, 0xc6, 0x25, 0xd9, 0xdc, 0xb8, 0x5b, 0x96, 0x04, 0xeb, 0x60, 0x17, 0xaa,
	0xa8, 0xd3, 0xd9, 0xc0, 0x92, 0xc9, 0xff, 0xd0, 0x92, 0x22, 0x03, 0xd0, 0x64, 0x95, 0x79, 0x91,
	0xc1, 0x86, 0x6f, 0x80, 0xa1, 0xa7, 0x79, 0x42, 0x2c, 0xe3, 0xb4, 0xad, 0xeb, 0x0a, 0x54, 0x6f,
	0x89, 0x2d, 0xc4, 0x3e, 0x82, 0x75, 0x55, 0xa2, 0xe1, 0x0b, 0x60, 0xce, 0x20, 0x3d, 0x1b, 0x9f,
	0x99, 0xa8, 0x5e, 0xc9, 0x93, 0x27, 0x6b, 0xe3, 0xde, 0xc5, 0xdd, 0xf0, 0x3d, 0x84, 0x9a, 0x2c,
	0x9f, 0x7e, 0x81, 0x7d, 0xe3, 0x6a, 0xf6, 0x7b, 0x74, 0x3c, 0xf1, 0x77, 0x89, 0xae, 0x23, 0xbf,
	0x35, 0x67, 0x7e, 0xe8, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x01, 0xc3, 0xdf, 0xff, 0x00,
	0x00, 0x00,
}
